#!/bin/sh

# script/setup: First time setup

set -e

cd "$(dirname "$0")/.."

verify_homebrew_installation() {
  command -v brew >/dev/null 2>&1 || {
      echo "=> Homebrew is required!"
      echo "==> Visit https://brew.sh/ for installation instructions."
      exit 1
  }
}

install_homebrew_packages() {
  BREWFILE=${BREWFILE:-Brewfile}
  if [ -f "$BREWFILE" ] && [ "$(uname -s)" = "Darwin" ]; then
    brew bundle check >/dev/null 2>&1  || {
      echo "=> Installing Homebrew packages defined in $BREWFILE"
      brew bundle
    }
  fi
}

install_npm_dependencies() {
  npm install
}

setup() {
  echo "> Setup starting."
  verify_homebrew_installation
  install_homebrew_packages
  install_npm_dependencies
  echo "> Setup complete."
}

setup
